import { pool, withTransaction } from '../../api/src/db.js';

async function processQueuedRecap() {
  const job = await withTransaction(async (client) => {
    const claim = await client.query(
      `SELECT id, campaign_id, session_id, prompt_version
       FROM ai_job_runs
       WHERE status = 'queued' AND job_type = 'session_recap'
       ORDER BY queued_at ASC
       FOR UPDATE SKIP LOCKED
       LIMIT 1`
    );

    if (!claim.rows[0]) return null;

    await client.query(`UPDATE ai_job_runs SET status = 'running', started_at = NOW() WHERE id = $1`, [claim.rows[0].id]);
    return claim.rows[0];
  });

  if (!job) return false;

  await withTransaction(async (client) => {
    const events = await client.query(
      `SELECT event_type, payload_json, ts
       FROM game_events
       WHERE session_id = $1
       ORDER BY ts ASC`,
      [job.session_id]
    );

    const summary = `Session contained ${events.rowCount} timeline events. Key ending state captured for investor demo.`;

    await client.query(
      `INSERT INTO session_recaps (
        campaign_id, session_id, status, short_recap_markdown, long_recap_markdown,
        source_coverage_json, model_name, prompt_version, token_input, token_output, estimated_cost_usd, completed_at
      ) VALUES ($1, $2, 'completed', $3, $4, $5::jsonb, 'deterministic-demo-writer', $6, 0, 0, 0, NOW())`,
      [
        job.campaign_id,
        job.session_id,
        summary,
        `${summary}\n\nThis recap was generated by deterministic demo worker logic.`,
        JSON.stringify({ covered_event_ids: [], omitted_high_importance_event_ids: [] }),
        job.prompt_version ?? 'recap-v1'
      ]
    );

    await client.query(`UPDATE ai_job_runs SET status = 'completed', completed_at = NOW() WHERE id = $1`, [job.id]);
  });

  return true;
}

async function run() {
  while (true) {
    const worked = await processQueuedRecap();
    if (!worked) await new Promise((resolve) => setTimeout(resolve, 1500));
  }
}

run();
